import Container from '@/components/container';
import Header from '@/components/header';
import { TextInput } from '@/components/inputs/textInput';
import Head from 'next/head';
import { useState } from 'react';

export default function Home() {
  const [title, setTitle] = useState('');
  return (
    <>
      <Head>
        <title>5 N&apos; Dine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container tx={{ px: 2 }}>
        <TextInput
          value={title}
          onChange={setTitle}
          id="title"
          label="TItle"
          helperText="Write a title"
        />
      </Container>
    </>
  );
}
