import Container from '@/components/container';
import Header from '@/components/header';
import Head from 'next/head';
import { Box } from 'theme-ui';

export default function Home() {
  return (
    <>
      <Head>
        <title>5 N&apos; Dine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Container tx={{ px: 2, background: 'purple' }}>
          <Box
            sx={{
              height: 100,
              width: '100%',
              background: 'green',
            }}
          ></Box>
        </Container>
      </main>
    </>
  );
}
